/*
 * This source file was generated by the Gradle 'init' task
 */
package celestial.example;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello, Celestial Bodies!");
    }
}
