/*
 * This source file was generated by the Gradle 'init' task
 */

package celestial.example;

import celestial.data.Data;
import celestial.data.DataLoader;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.println("Hello, Celestial Bodies!");

        Path dataPath = Paths.get("data");
        if (!Files.exists(dataPath)) {
            dataPath = Paths.get("../data");
        }

        System.out.printf("Load data from dir: %s%n", dataPath.toAbsolutePath());

        Data data = DataLoader.loadData(dataPath);
        Map<String, Object> objects = data.getObjects();
        Map<String, Object> systems = data.getSystems();

        System.out.printf("Loaded objects: %d%n", objects.size());
        for (String key : objects.keySet()) {
            System.out.printf("  key: %s, object: %s%n", key, objects.get(key));
        }

        System.out.printf("Loaded systems: %d%n", systems.size());
        for (String key : systems.keySet()) {
            System.out.printf("  key: %s, system: %s%n", key, systems.get(key));
        }
    }
}
